package com.sample.sort.model.eo;

import oracle.jbo.server.EntityCache;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Jun 12 15:46:02 EDT 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class EmployeeCollImpl extends EntityCache {
    /**
     * This is the default constructor (do not remove).
     */
    public EmployeeCollImpl() {
    }
}

